name:                aoc
version:             0.1.0.0
github:              "githubuser/aoc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

data-files:
  - day-1/input.txt
  - day-2/input.txt

executables:
  day-1:
    main:                Main.hs
    source-dirs:         day-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
  day-2:
    main:                Main.hs
    source-dirs:         day-2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
